services:
  - type: web
    name: client
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://Phodzo:Phodzo24@mern.e2ocybl.mongodb.net/?retryWrites=true&w=majority&appName=mern
  - type: web
    name: api
    env: node
    buildCommand: npm install && npm start
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://Phodzo:Phodzo24@mern.e2ocybl.mongodb.net/?retryWrites=true&w=majority&appName=mern
